fix(SQL): Improve sql queries for mod-progression
azerothcore/mod-progression-system pull request #264
Opened 2022-11-17 02:15 UTC by Gultask

- Use SpawnMask instead of deleting creatures
 - Hides quests in Silithus instead of NPCs
 - Uses new GUIDs for Love is in the Air NPCs
 - Other minor fixes

2022-11-17 05:47 UTC, Gultask commented
If you already have the creatures deleted, here are the INSERT queries for them. I may have missed a few. These are from the latest AC revision at the time of writing.

https://gist.github.com/Gultask/e5a3c706f1e5ce6dbdb87b5210977ed5

2022-11-17 06:54 UTC, temperrr requested changes

2022-11-17 06:54 UTC, temperrr commented on src/Bracket_0/sql/world/progression_0_quest.sql
> +DELETE FROM `creature_queststarter` WHERE `quest` IN (
Quests can also be disabled https://www.azerothcore.org/wiki/disables

2022-11-17 19:07 UTC, Nyeriah approved these changes

2022-11-18 20:42 UTC, Samsequel approved these changes

2022-11-30 23:55 UTC, merged